blank_issues_enabled: false
contact_links:
  - name: ğŸ“¨ í”„ë¡œí•„
    url:
    about: Please ask and answer questions here.
  - name: ğŸŒ í”„ë¡œì íŠ¸
    url:
    about: Please report security vulnerabilities here.